.gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -27,29 +27,36 @@ build:
 test:
   stage: test
   script:
-  # Cleanup
-  - docker compose down -v --remove-orphans > /dev/null 2>&1 || true
-  - docker system prune -f > /dev/null 2>&1 || true
+    # Cleanup
+    - docker compose down -v --remove-orphans > /dev/null 2>&1 || true
+    - docker system prune -f > /dev/null 2>&1 || true
 
-  # Start containers
-  - docker compose up -d --build
+    # Start containers
+    - docker compose up -d --build
 
-  # Install dependencies inside app container
-  - docker compose exec -T app composer install --no-interaction --optimize-autoloader
+    # Fix permissions for composer & git
+    - docker compose exec -T --user root app chown -R www-data:www-data /var/www
+    - docker compose exec -T --user root app git config --global --add safe.directory /var/www
 
-  # Wait for database
-  - |
-    for i in {1..20}; do
-      docker compose exec -T app php artisan migrate:status > /dev/null 2>&1 && break
-      echo "Database not ready yet, retrying..."
-      sleep 3
-    done
+    # Install dependencies
+    - docker compose exec -T app composer install --no-interaction --optimize-autoloader
 
-  # Run migrations
-  - docker compose exec -T app php artisan migrate --force
+    # Wait for database
+    - |
+      for i in {1..20}; do
+        docker compose exec -T app php artisan migrate:status > /dev/null 2>&1 && break
+        echo "Database not ready yet, retrying..."
+        sleep 3
+      done
 
-  # Run tests
-  - docker compose exec -T app php artisan test --stop-on-failure
+    # Run migrations
+    - docker compose exec -T app php artisan migrate --force
+
+    # Run tests
+    - docker compose exec -T app php artisan test --stop-on-failure
+
+  after_script:
+    - docker compose down -v --remove-orphans > /dev/null 2>&1 || true
 
 
 deploy:
